name: Deploy to staging
on:
    push:
        branches: 
          - main
jobs:
    redeploy_everything:
        name: Deploying everything on staging
        runs-on: ubuntu-latest
        steps: 
            - name: multiple command
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: 3.109.155.201
                username: ubuntu
                key: ${{ secrets.PRIVATE_SSH_KEY }}
                port: 22
                script: | 
                    cd monorepo-deploy
                    git pull origin main
                    export PATH=/home/ubuntu/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
                    npm i -g pnpm
                    pnpm install
                    pnpm run build
                    pm2 restart fe-server
                    pm2 restart http-server
                    pm2 restart ws-server


