name: Deploy to staging
on:
    push:
        branches: 
          - main
jobs:
    redeploy_everything:
        name: Deploying everything on staging
        runs-on: ubuntu-latest
        steps: 
            - name: multiple command
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: 13.233.104.115
                username: ubuntu
                key: ${{ secrets.PRIVATE_SSH_KEY }}
                port: 22
                script: | 
                    cd monorepo-deploy
                    git pull origin main
                    export NVM_DIR=~/.nvm
                    source ~/.nvm/nvm.sh
                    pnpm install
                    pnpm run build
                    pm2 restart fe-server
                    pm2 restart http-server
                    pm2 restart ws-server


